/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rusfort (https://sketchfab.com/Rusfort)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/xbox-elite-controller-32aad0ff25f7446b8afe649ea3cc9e43
Title: Xbox Elite Controller
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Cube002_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle002_glass_0: THREE.Mesh;
    Circle003_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle004_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle006_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle007_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle008_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Cube003_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Plane001_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle009_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Text_Material001_0: THREE.Mesh;
    Text001_Material001_0: THREE.Mesh;
    Text002_Material001_0: THREE.Mesh;
    Text003_Material001_0: THREE.Mesh;
    Circle010_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Cube005_TT_checker_1024x1024_UV_GRID_0: THREE.Mesh;
    Circle011_TT_checker_1024x1024_UV_GRID001_0: THREE.Mesh;
  };
  materials: {
    TT_checker_1024x1024_UV_GRID: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["TT_checker_1024x1024_UV_GRID.001"]: THREE.MeshStandardMaterial;
  };
};

export function ControllerModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/assets/models/xbox_elite_controller/scene.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[-2.011, -1.043, 2.152]}
        rotation={[-0.268, -0.033, 0.008]}
        scale={100.706}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[-3.94, 1.498, 1.328]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002_glass_0.geometry}
        material={materials.glass}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[0, 3.353, -0.822]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[-2.014, -1.853, 0.857]}
        rotation={[-0.432, -0.042, 0.007]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[3.104, 1.312, 1.164]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[2.425, 1.45, 1.453]}
        rotation={[-0.428, 0, 0]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[3.595, 2.428, 1.007]}
        rotation={[-0.428, 0, 0]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[4.633, 1.302, 1.105]}
        rotation={[-0.502, 0.37, 0.027]}
        scale={0.896}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[3.574, 0.438, 1.914]}
        rotation={[-0.428, 0, 0]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle010_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[-0.006, -0.298, 0.078]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_TT_checker_1024x1024_UV_GRID_0.geometry}
        material={materials.TT_checker_1024x1024_UV_GRID}
        position={[1.98, -0.796, 2.259]}
        rotation={[-0.299, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011_TT_checker_1024x1024_UV_GRID001_0.geometry}
        material={materials["TT_checker_1024x1024_UV_GRID.001"]}
        position={[-0.006, -0.297, 0.08]}
        rotation={[-0.428, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/xbox_elite_controller/scene.gltf");
